name: Generar APK Zona PC Nativo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Usamos un generador de confianza que sí existe
      - name: Fabricar Webview Real
        uses: swisspost/web-to-app-action@v1
        with:
          url: https://abregur2011.github.io/Digital-Store/
          name: "Digital Store"
          package-id: "com.zonapc.digitalstore"
          # Permisos para que la TV Box no se queje
          android-permissions: "INTERNET, REQUEST_INSTALL_PACKAGES"

      - name: Subir APK de Zona PC
        uses: actions/upload-artifact@v4
        with:
          name: Digital-Store-ZPC
          path: "*.apk"
